[tool.ruff]
target-version = "py312"
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "B", "I", "UP"]
ignore = ["D", "RUF001", "RUF003", "INP001", "EM101", "PLW2901"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*.py" = ["S101"]

[tool.ruff.lint.isort]
known-first-party = ["cfg", "hw", "mgr", "net", "ui", "utils"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
